/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zonaVisual;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import zonaNegocio.*;
/**
 * JPanel
 * Muestra los usuarios registrados en Javapop al administrador
 */
public class MostrarUsuarios extends javax.swing.JPanel {

     private JFrame ventanaprincipal;

    public  JFrame getVentanaprincipal() {
        
        return ventanaprincipal;
    }

    
    public void setVentanaprincipal(JFrame ventanaprincipal) {
        this.ventanaprincipal = ventanaprincipal;
    }
    
    public MostrarUsuarios() {
        initComponents();
    }

    /**
     * Genera la tabla con los usuarios de la apliación
     */
    public void generarTabla(){
       
        int j = 0;
        //Aquí quitamos 1 al tamaño de la aplicacion ya que el administrador no debe de aparecer en la tabla.
        String listaProductos[][] = new String[((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().size()-1][this.tabla.getColumnCount()];       
        String nombreColumnas[] = {"Nombre","DNI","Tipo","Correo","Estado"};
        for (j = 1; j < ((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().size(); j++){
            listaProductos[j-1][0] = ((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(j)).getNombre();
            listaProductos[j-1][1] = ((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(j)).getDni();
            listaProductos[j-1][2] = ((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(j)).getClass().getSimpleName();
            listaProductos[j-1][3] = ((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(j)).getCorreo();
            listaProductos[j-1][4] = ((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(j)).getEstado().toString();
                    
            
            
        }
        DefaultTableModel model = new DefaultTableModel(listaProductos, nombreColumnas);
        tabla.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios Javapop");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Tipo", "Correo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Consultar Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tabla.getSelectedRowCount()!=0){
        registro rgf = new registro();
        rgf.setVentanaprincipal(this.getVentanaprincipal());
        rgf.setVisible(true);
        rgf.mostrarDatosCliente((Cliente)((VentanaPrincipal) getVentanaprincipal()).getJavapop().getUsuarios().get(tabla.getSelectedRow()+1));
        rgf.consultaAdministrador();
       
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.generarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
