/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zonaVisual;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import zonaNegocio.*;

/**
 *
 * @author ismae
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private JFrame añadirproducto;
    
    public JFrame getAñadirproducto(){
        return añadirproducto;
    }
    
    public void setAñadirproducto(JFrame añadirproducto){
        this.añadirproducto = añadirproducto;
        
    }
    
    
    
    private Administrador admin = null;
    private Usuario usuarioConectado;
    private JavaPop javapop;
    
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("JAVAPOP");
        this.javapop = new JavaPop();
        // Traer informacion disco duro (Serializacion)
        if (javapop.getUsuarios().isEmpty()){
           this.admin = new Administrador();
           this.javapop.getUsuarios().add(admin); 
        }
        JFrame login = new Login(this);
        
        
    }

    public JavaPop getJavapop() {
        return javapop;
    }

    public void setJavapop(JavaPop javapop) {
        this.javapop = javapop;
    }
    
    
    public Usuario getUsuarioConectado() {
        return usuarioConectado;
    }

    public void setUsuarioConectado(Usuario usuarioConectado) {
        this.usuarioConectado = usuarioConectado;
    }

    public JLabel getUsuario() {
        return usuario;
    }

    public void setUsuario(JLabel usuario) {
        this.usuario = usuario;
    }
    
   
    public void añadirUsuario(Usuario usuario){
        javapop.getUsuarios().add(usuario);
    }

    
    
    public Administrador getAdmin() {
        return admin;
    }

    public void setAdmin(Administrador admin) {
        this.admin = admin;
    }
    public void actualizarMenus(){
    if (!getUsuarioConectado().equals(admin)){
            MenuAdministrador.setVisible(false);
            MenuCliente.setVisible(true);
        } else {
            MenuCliente.setVisible(false);
            MenuAdministrador.setVisible(true);
        }
        if (!getUsuarioConectado().getClass().getSimpleName().equals("ClienteProfesional")){
            CuentaProfesional.setVisible(false);
        } else {
            CuentaProfesional.setVisible(true);
        }
    }
   
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdministrador = new javax.swing.JMenu();
        MostrarProductos = new javax.swing.JMenuItem();
        MostrarUsuarios = new javax.swing.JMenuItem();
        MostrarVentas = new javax.swing.JMenuItem();
        MenuCliente = new javax.swing.JMenu();
        Vender = new javax.swing.JMenuItem();
        Comprar = new javax.swing.JMenuItem();
        CuentaProfesional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        MenuAdministrador.setText("Administrador");

        MostrarProductos.setText("Mostrar productos");
        MenuAdministrador.add(MostrarProductos);

        MostrarUsuarios.setText("Mostrar usuarios");
        MostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarUsuariosActionPerformed(evt);
            }
        });
        MenuAdministrador.add(MostrarUsuarios);

        MostrarVentas.setText("Mostrar ventas ");
        MostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarVentasActionPerformed(evt);
            }
        });
        MenuAdministrador.add(MostrarVentas);

        jMenuBar1.add(MenuAdministrador);

        MenuCliente.setText("Cliente");

        Vender.setText("Vender");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });
        MenuCliente.add(Vender);

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        MenuCliente.add(Comprar);

        CuentaProfesional.setText("Cuenta Profesional");
        CuentaProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaProfesionalActionPerformed(evt);
            }
        });
        MenuCliente.add(CuentaProfesional);

        jMenuBar1.add(MenuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(783, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    @Override
    public Image getIconImage() {
        try{
            Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("contents/java.jpg"));
            return retValue;
        }
        catch (Exception e){
           return (null); 
        }
    }
    
    private void MostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarUsuariosActionPerformed

    private void MostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarVentasActionPerformed

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderActionPerformed
         DetalleProducto vender = new DetalleProducto();
         vender.setVentanaprincipal(this);
         vender.setVisible(true);
         vender.setModoNuevoProducto();
    }//GEN-LAST:event_VenderActionPerformed

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        jPanel1.removeAll();
        jPanel1.add(new BusquedaProducto());
        jPanel1.updateUI();
        
    }//GEN-LAST:event_ComprarActionPerformed

    private void CuentaProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaProfesionalActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_CuentaProfesionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal();
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JMenuItem CuentaProfesional;
    private javax.swing.JMenu MenuAdministrador;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenuItem MostrarProductos;
    private javax.swing.JMenuItem MostrarUsuarios;
    private javax.swing.JMenuItem MostrarVentas;
    private javax.swing.JMenuItem Vender;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
